import type { SupportedLocale } from "@/lib/i18n";

export type HistoryMessages = {
  link: string;
  title: string;
  original: string;
  restoration: string;
  modern: string;
  sources: string;
  back: string;
};

type HistoryTuple = readonly [string, string, string, string, string, string, string];

const translations = {
  en: ["History", "teuteuteu.com, a restored piece of the 2000s web", "Documented online by 2005, the original Flash page did almost nothing: one blue button played an absurd sound while the browser window shook.", "The surviving SWF was analysed to recover its button images, audio and the exact timeline of 166 shakes. Web Audio now reproduces the sequence without a Flash plugin.", "Accessibility, 51 languages, the global click counter and the supporter list are modern additions. The empty white page and its strange joke remain intact.", "Sources", "Back to the button"],
  fr: ["Histoire", "teuteuteu.com, un morceau restauré du web des années 2000", "Documentée en ligne dès 2005, la page Flash originale ne faisait presque rien : un bouton bleu lançait un son absurde pendant que la fenêtre du navigateur tremblait.", "Le SWF conservé a été analysé pour retrouver les images du bouton, l’audio et la chronologie exacte de 166 secousses. Web Audio reproduit maintenant la séquence sans plugin Flash.", "L’accessibilité, les 51 langues, le compteur mondial et la liste des donateurs sont des ajouts modernes. La page blanche vide et son étrange blague restent intactes.", "Sources", "Retour au bouton"],
  de: ["Geschichte", "teuteuteu.com, ein restauriertes Stück Web der 2000er", "Die bereits 2005 dokumentierte Flash-Seite tat fast nichts: Ein blauer Knopf spielte einen absurden Ton, während das Browserfenster wackelte.", "Die erhaltene SWF-Datei wurde analysiert, um Knopfbilder, Ton und den exakten Ablauf von 166 Erschütterungen zurückzugewinnen. Web Audio spielt ihn heute ohne Flash-Plugin ab.", "Barrierefreiheit, 51 Sprachen, der weltweite Klickzähler und die Unterstützerliste sind moderne Ergänzungen. Die leere weiße Seite und ihr seltsamer Witz bleiben erhalten.", "Quellen", "Zurück zum Knopf"],
  es: ["Historia", "teuteuteu.com, una pieza restaurada de la web de los 2000", "Documentada en internet desde 2005, la página Flash original casi no hacía nada: un botón azul reproducía un sonido absurdo mientras la ventana del navegador temblaba.", "Se analizó el SWF conservado para recuperar las imágenes del botón, el audio y la secuencia exacta de 166 sacudidas. Web Audio la reproduce ahora sin plugin Flash.", "La accesibilidad, los 51 idiomas, el contador mundial y la lista de donantes son añadidos modernos. La página blanca vacía y su extraña broma siguen intactas.", "Fuentes", "Volver al botón"],
  it: ["Storia", "teuteuteu.com, un pezzo restaurato del web anni 2000", "Documentata online già nel 2005, la pagina Flash originale non faceva quasi nulla: un pulsante blu riproduceva un suono assurdo mentre la finestra del browser tremava.", "Il file SWF sopravvissuto è stato analizzato per recuperare immagini, audio e la sequenza esatta di 166 scosse. Web Audio ora la riproduce senza plugin Flash.", "Accessibilità, 51 lingue, contatore globale e lista dei sostenitori sono aggiunte moderne. La pagina bianca vuota e la sua strana battuta restano intatte.", "Fonti", "Torna al pulsante"],
  "pt-PT": ["História", "teuteuteu.com, um pedaço restaurado da web dos anos 2000", "Documentada online desde 2005, a página Flash original quase nada fazia: um botão azul tocava um som absurdo enquanto a janela do navegador tremia.", "O SWF preservado foi analisado para recuperar as imagens do botão, o áudio e a sequência exata de 166 abanões. A Web Audio reproduz agora tudo sem plugin Flash.", "A acessibilidade, 51 idiomas, o contador mundial e a lista de apoiantes são adições modernas. A página branca vazia e a sua estranha piada permanecem intactas.", "Fontes", "Voltar ao botão"],
  "pt-BR": ["História", "teuteuteu.com, um pedaço restaurado da web dos anos 2000", "Documentada online desde 2005, a página Flash original quase não fazia nada: um botão azul tocava um som absurdo enquanto a janela do navegador tremia.", "O SWF preservado foi analisado para recuperar as imagens do botão, o áudio e a sequência exata de 166 tremidas. A Web Audio agora reproduz tudo sem plugin Flash.", "A acessibilidade, 51 idiomas, o contador mundial e a lista de apoiadores são adições modernas. A página branca vazia e sua piada estranha continuam intactas.", "Fontes", "Voltar ao botão"],
  nl: ["Geschiedenis", "teuteuteu.com, een gerestaureerd stukje web uit de jaren 2000", "De al in 2005 online beschreven Flash-pagina deed bijna niets: één blauwe knop speelde een absurd geluid terwijl het browservenster schudde.", "Het bewaarde SWF-bestand is geanalyseerd om de knopafbeeldingen, audio en exacte reeks van 166 schokken terug te halen. Web Audio speelt die nu af zonder Flash-plugin.", "Toegankelijkheid, 51 talen, de wereldwijde teller en de donateurslijst zijn moderne toevoegingen. De lege witte pagina en haar vreemde grap blijven intact.", "Bronnen", "Terug naar de knop"],
  pl: ["Historia", "teuteuteu.com, odrestaurowany fragment internetu lat 2000", "Udokumentowana w sieci już w 2005 roku strona Flash prawie nic nie robiła: niebieski przycisk odtwarzał absurdalny dźwięk, a okno przeglądarki drżało.", "Zachowany plik SWF przeanalizowano, odzyskując obrazy przycisku, dźwięk i dokładną sekwencję 166 wstrząsów. Web Audio odtwarza ją dziś bez wtyczki Flash.", "Dostępność, 51 języków, światowy licznik i lista wspierających to nowoczesne dodatki. Pusta biała strona i jej dziwny żart pozostały nietknięte.", "Źródła", "Wróć do przycisku"],
  cs: ["Historie", "teuteuteu.com, obnovený kousek webu z nultých let", "Původní stránka ve Flashi, doložená online už v roce 2005, téměř nic nedělala: modré tlačítko spustilo absurdní zvuk a okno prohlížeče se třáslo.", "Dochovaný SWF byl analyzován a podařilo se získat obrázky tlačítka, zvuk i přesnou časovou osu 166 otřesů. Web Audio ji dnes přehrává bez pluginu Flash.", "Přístupnost, 51 jazyků, globální počítadlo a seznam podporovatelů jsou moderní doplňky. Prázdná bílá stránka a její podivný vtip zůstaly zachovány.", "Zdroje", "Zpět k tlačítku"],
  sk: ["História", "teuteuteu.com, obnovený kúsok webu z rokov 2000", "Pôvodná stránka vo Flashi, zdokumentovaná už v roku 2005, takmer nič nerobila: modré tlačidlo spustilo absurdný zvuk a okno prehliadača sa triaslo.", "Zachovaný SWF bol analyzovaný a podarilo sa získať obrázky tlačidla, zvuk aj presnú časovú os 166 otrasov. Web Audio ju dnes prehráva bez pluginu Flash.", "Prístupnosť, 51 jazykov, globálne počítadlo a zoznam podporovateľov sú moderné doplnky. Prázdna biela stránka a jej zvláštny vtip zostali zachované.", "Zdroje", "Späť k tlačidlu"],
  hu: ["Történet", "teuteuteu.com, a 2000-es évek webének helyreállított darabja", "A már 2005-ban dokumentált eredeti Flash-oldal szinte semmit sem csinált: egy kék gomb abszurd hangot játszott, miközben a böngészőablak rázkódott.", "A fennmaradt SWF elemzésével visszanyertük a gomb képeit, a hangot és a 166 rázkódás pontos idővonalát. A Web Audio ma Flash-bővítmény nélkül játssza le.", "Az akadálymentesség, az 51 nyelv, a globális számláló és a támogatói lista modern kiegészítés. Az üres fehér oldal és furcsa tréfája érintetlen maradt.", "Források", "Vissza a gombhoz"],
  ro: ["Istorie", "teuteuteu.com, o bucată restaurată din webul anilor 2000", "Documentată online încă din 2005, pagina Flash originală nu făcea aproape nimic: un buton albastru reda un sunet absurd în timp ce fereastra browserului se zguduia.", "Fișierul SWF păstrat a fost analizat pentru a recupera imaginile butonului, sunetul și cronologia exactă a 166 de zguduiri. Web Audio redă acum secvența fără plugin Flash.", "Accesibilitatea, 51 de limbi, contorul global și lista susținătorilor sunt adăugiri moderne. Pagina albă goală și gluma ei ciudată rămân intacte.", "Surse", "Înapoi la buton"],
  bg: ["История", "teuteuteu.com, възстановена частица от мрежата на 2000-те", "Документирана онлайн още през 2005 г., оригиналната Flash страница почти не правеше нищо: син бутон пускаше абсурден звук, докато прозорецът на браузъра се тресеше.", "Запазеният SWF беше анализиран, за да се възстановят изображенията на бутона, звукът и точната поредица от 166 разтърсвания. Web Audio вече я възпроизвежда без Flash плъгин.", "Достъпността, 51 езика, глобалният брояч и списъкът с дарители са съвременни добавки. Празната бяла страница и странната ѝ шега остават непокътнати.", "Източници", "Обратно към бутона"],
  el: ["Ιστορία", "teuteuteu.com, ένα αποκατεστημένο κομμάτι του ιστού των 2000s", "Καταγεγραμμένη online ήδη από το 2005, η αρχική σελίδα Flash δεν έκανε σχεδόν τίποτα: ένα μπλε κουμπί έπαιζε έναν παράλογο ήχο ενώ το παράθυρο του browser σειόταν.", "Το σωζόμενο SWF αναλύθηκε για να ανακτηθούν οι εικόνες του κουμπιού, ο ήχος και η ακριβής ακολουθία 166 δονήσεων. Το Web Audio την αναπαράγει πλέον χωρίς Flash plugin.", "Η προσβασιμότητα, οι 51 γλώσσες, ο παγκόσμιος μετρητής και η λίστα υποστηρικτών είναι σύγχρονες προσθήκες. Η κενή λευκή σελίδα και το παράξενο αστείο της μένουν ανέπαφα.", "Πηγές", "Πίσω στο κουμπί"],
  tr: ["Tarihçe", "teuteuteu.com, 2000’ler webinden restore edilmiş bir parça", "2005’dan beri çevrimiçi belgelenen özgün Flash sayfası neredeyse hiçbir şey yapmıyordu: mavi bir düğme saçma bir ses çalarken tarayıcı penceresi sallanıyordu.", "Günümüze kalan SWF; düğme görsellerini, sesi ve 166 sarsıntının kesin zaman çizelgesini kurtarmak için incelendi. Web Audio artık bunu Flash eklentisi olmadan oynatıyor.", "Erişilebilirlik, 51 dil, küresel sayaç ve destekçi listesi modern eklemelerdir. Boş beyaz sayfa ve tuhaf şakası aynen korunmuştur.", "Kaynaklar", "Düğmeye dön"],
  ru: ["История", "teuteuteu.com — восстановленный фрагмент интернета 2000-х", "Оригинальная Flash-страница, упоминавшаяся в сети уже в 2005 году, почти ничего не делала: синяя кнопка включала абсурдный звук, а окно браузера тряслось.", "Сохранившийся SWF был разобран, чтобы вернуть изображения кнопки, звук и точную последовательность 166 встрясок. Web Audio теперь воспроизводит её без Flash-плагина.", "Доступность, 51 язык, мировой счётчик и список поддержавших — современные дополнения. Пустая белая страница и её странная шутка остались нетронутыми.", "Источники", "Вернуться к кнопке"],
  uk: ["Історія", "teuteuteu.com — відновлений фрагмент інтернету 2000-х", "Оригінальна Flash-сторінка, згадувана в мережі вже 2005 року, майже нічого не робила: синя кнопка вмикала абсурдний звук, а вікно браузера тремтіло.", "Збережений SWF проаналізували, щоб повернути зображення кнопки, звук і точну послідовність 166 струсів. Web Audio тепер відтворює її без Flash-плагіна.", "Доступність, 51 мова, світовий лічильник і список підтримки — сучасні доповнення. Порожня біла сторінка та її дивний жарт залишилися недоторканими.", "Джерела", "Повернутися до кнопки"],
  sv: ["Historia", "teuteuteu.com, en restaurerad bit av 2000-talets webb", "Flash-sidan, dokumenterad på nätet redan 2005, gjorde nästan ingenting: en blå knapp spelade ett absurt ljud medan webbläsarfönstret skakade.", "Den bevarade SWF-filen analyserades för att återfå knappbilderna, ljudet och den exakta följden av 166 skakningar. Web Audio spelar nu upp den utan Flash-plugin.", "Tillgänglighet, 51 språk, den globala räknaren och supporterlistan är moderna tillägg. Den tomma vita sidan och dess märkliga skämt är bevarade.", "Källor", "Tillbaka till knappen"],
  no: ["Historie", "teuteuteu.com, en restaurert bit av nettet fra 2000-tallet", "Flash-siden, dokumentert på nettet allerede i 2005, gjorde nesten ingenting: en blå knapp spilte en absurd lyd mens nettleservinduet ristet.", "Den bevarte SWF-filen ble analysert for å hente ut knappbildene, lyden og den nøyaktige rekken av 166 rystelser. Web Audio spiller den nå uten Flash-programtillegg.", "Tilgjengelighet, 51 språk, den globale telleren og støttelisten er moderne tillegg. Den tomme hvite siden og den rare vitsen er bevart.", "Kilder", "Tilbake til knappen"],
  da: ["Historie", "teuteuteu.com, et restaureret stykke af 2000’ernes web", "Flash-siden, dokumenteret online allerede i 2005, gjorde næsten ingenting: en blå knap afspillede en absurd lyd, mens browservinduet rystede.", "Den bevarede SWF-fil blev analyseret for at genskabe knapbillederne, lyden og den præcise række af 166 rystelser. Web Audio afspiller den nu uden Flash-plugin.", "Tilgængelighed, 51 sprog, den globale tæller og støttelisten er moderne tilføjelser. Den tomme hvide side og dens mærkelige joke er bevaret.", "Kilder", "Tilbage til knappen"],
  fi: ["Historia", "teuteuteu.com, entisöity pala 2000-luvun verkkoa", "Jo vuonna 2005 verkossa dokumentoitu alkuperäinen Flash-sivu ei tehnyt juuri mitään: sininen painike soitti absurdin äänen samalla kun selainikkuna tärisi.", "Säilynyt SWF analysoitiin, jotta painikkeen kuvat, ääni ja 166 tärähdyksen tarkka aikajana saatiin talteen. Web Audio toistaa sen nyt ilman Flash-lisäosaa.", "Saavutettavuus, 51 kieltä, maailmanlaajuinen laskuri ja tukijalista ovat uusia lisäyksiä. Tyhjä valkoinen sivu ja sen outo vitsi säilyvät ennallaan.", "Lähteet", "Takaisin painikkeeseen"],
  et: ["Ajalugu", "teuteuteu.com, taastatud killuke 2000. aastate veebist", "Juba 2005. aastal veebis dokumenteeritud Flash-leht ei teinud peaaegu midagi: sinine nupp mängis absurdset heli ja brauseriaken värises.", "Säilinud SWF-i analüüsiti, et taastada nupu pildid, heli ja 166 raputuse täpne ajajoon. Web Audio esitab selle nüüd ilma Flashi pistikprogrammita.", "Ligipääsetavus, 51 keelt, üleilmne loendur ja toetajate nimekiri on tänapäevased lisad. Tühi valge leht ja selle kummaline nali on puutumata.", "Allikad", "Tagasi nupu juurde"],
  lv: ["Vēsture", "teuteuteu.com, atjaunots 2000. gadu tīmekļa fragments", "Jau 2005. gadā tiešsaistē dokumentētā Flash lapa gandrīz neko nedarīja: zila poga atskaņoja absurdu skaņu, kamēr pārlūka logs drebēja.", "Saglabātais SWF tika analizēts, lai atgūtu pogas attēlus, audio un precīzu 166 satricinājumu laika līniju. Web Audio to tagad atskaņo bez Flash spraudņa.", "Pieejamība, 51 valoda, globālais skaitītājs un atbalstītāju saraksts ir mūsdienīgi papildinājumi. Tukšā baltā lapa un tās dīvainais joks paliek neskarti.", "Avoti", "Atpakaļ pie pogas"],
  lt: ["Istorija", "teuteuteu.com, atkurtas 2000-ųjų interneto fragmentas", "Dar 2005 m. internete aprašytas Flash puslapis beveik nieko nedarė: mėlynas mygtukas grojo absurdišką garsą, o naršyklės langas drebėjo.", "Išlikęs SWF buvo išanalizuotas, kad būtų atkurti mygtuko vaizdai, garsas ir tiksli 166 sukrėtimų seka. Web Audio dabar ją atkuria be Flash papildinio.", "Prieinamumas, 51 kalba, pasaulinis skaitiklis ir rėmėjų sąrašas yra šiuolaikiniai priedai. Tuščias baltas puslapis ir jo keistas pokštas liko nepakeisti.", "Šaltiniai", "Grįžti prie mygtuko"],
  sl: ["Zgodovina", "teuteuteu.com, obnovljen košček spleta iz 2000-ih", "Izvirna stran Flash, dokumentirana že leta 2005, ni počela skoraj ničesar: moder gumb je predvajal absurden zvok, okno brskalnika pa se je treslo.", "Ohranjeni SWF je bil analiziran za obnovitev slik gumba, zvoka in natančnega zaporedja 166 tresljajev. Web Audio ga zdaj predvaja brez vtičnika Flash.", "Dostopnost, 51 jezikov, globalni števec in seznam podpornikov so sodobni dodatki. Prazna bela stran in njena čudna šala ostajata nedotaknjeni.", "Viri", "Nazaj na gumb"],
  hr: ["Povijest", "teuteuteu.com, obnovljeni komadić weba iz 2000-ih", "Izvorna Flash stranica, zabilježena na internetu još 2005., nije radila gotovo ništa: plavi gumb puštao je apsurdan zvuk dok se prozor preglednika tresao.", "Sačuvani SWF analiziran je kako bi se vratile slike gumba, zvuk i točan slijed 166 potresa. Web Audio ga sada reproducira bez Flash dodatka.", "Pristupačnost, 51 jezik, globalni brojač i popis podržavatelja moderni su dodaci. Prazna bijela stranica i njezina čudna šala ostaju netaknute.", "Izvori", "Natrag na gumb"],
  sr: ["Историја", "teuteuteu.com, обновљени део веба из 2000-их", "Оригинална Flash страница, забележена на интернету још 2005, готово ништа није радила: плаво дугме пуштало је апсурдан звук док се прозор прегледача тресао.", "Сачувани SWF је анализиран да би се вратили слике дугмета, звук и тачан низ од 166 потреса. Web Audio га сада репродукује без Flash додатка.", "Приступачност, 51 језик, глобални бројач и списак подржавалаца су модерни додаци. Празна бела страница и њена чудна шала остају нетакнуте.", "Извори", "Назад на дугме"],
  bs: ["Historija", "teuteuteu.com, obnovljeni dio weba iz 2000-ih", "Originalna Flash stranica, zabilježena na internetu još 2005, gotovo ništa nije radila: plavo dugme puštalo je apsurdan zvuk dok se prozor preglednika tresao.", "Sačuvani SWF analiziran je kako bi se vratile slike dugmeta, zvuk i tačan niz od 166 potresa. Web Audio ga sada reprodukuje bez Flash dodatka.", "Pristupačnost, 51 jezik, globalni brojač i spisak podržavalaca moderni su dodaci. Prazna bijela stranica i njena čudna šala ostaju netaknute.", "Izvori", "Nazad na dugme"],
  sq: ["Historia", "teuteuteu.com, një pjesë e restauruar e uebit të viteve 2000", "Faqja origjinale Flash, e dokumentuar online që në 2005, pothuajse nuk bënte asgjë: një buton blu luante një tingull absurd ndërsa dritarja e shfletuesit dridhej.", "SWF-ja e ruajtur u analizua për të rikthyer figurat e butonit, audion dhe rrjedhën e saktë të 166 dridhjeve. Web Audio tani e luan pa shtojcë Flash.", "Aksesueshmëria, 51 gjuhë, numëruesi global dhe lista e mbështetësve janë shtesa moderne. Faqja e bardhë bosh dhe shakaja e saj e çuditshme mbeten të paprekura.", "Burimet", "Kthehu te butoni"],
  ca: ["Història", "teuteuteu.com, una peça restaurada del web dels anys 2000", "Documentada en línia des del 2005, la pàgina Flash original gairebé no feia res: un botó blau reproduïa un so absurd mentre la finestra del navegador tremolava.", "Es va analitzar l’SWF conservat per recuperar les imatges del botó, l’àudio i la seqüència exacta de 166 sacsejades. Web Audio ara la reprodueix sense connector Flash.", "L’accessibilitat, els 51 idiomes, el comptador mundial i la llista de col·laboradors són afegits moderns. La pàgina blanca buida i la seva broma estranya continuen intactes.", "Fonts", "Torna al botó"],
  eu: ["Historia", "teuteuteu.com, 2000ko hamarkadako webaren zati zaharberritua", "2005rako sarean dokumentatua zegoen jatorrizko Flash orriak ia ez zuen ezer egiten: botoi urdin batek soinu absurdoa jotzen zuen nabigatzailearen leihoa dardarka zegoen bitartean.", "Gordetako SWFa aztertu zen botoiaren irudiak, audioa eta 166 astinaldien denbora-lerro zehatza berreskuratzeko. Web Audiok Flash pluginik gabe erreproduzitzen du orain.", "Irisgarritasuna, 51 hizkuntza, kontagailu globala eta babesleen zerrenda gehigarri modernoak dira. Orri zuri hutsa eta haren txiste bitxia bere horretan daude.", "Iturriak", "Itzuli botoira"],
  gl: ["Historia", "teuteuteu.com, unha peza restaurada da web dos anos 2000", "Documentada en liña desde 2005, a páxina Flash orixinal case non facía nada: un botón azul reproducía un son absurdo mentres a xanela do navegador tremía.", "Analizouse o SWF conservado para recuperar as imaxes do botón, o audio e a secuencia exacta de 166 sacudidas. Web Audio reprodúcea agora sen complemento Flash.", "A accesibilidade, os 51 idiomas, o contador mundial e a lista de apoios son engadidos modernos. A páxina branca baleira e a súa estraña broma seguen intactas.", "Fontes", "Volver ao botón"],
  ga: ["Stair", "teuteuteu.com, píosa athchóirithe de ghréasán na 2000idí", "Bhí an leathanach Flash bunaidh doiciméadaithe ar líne faoi 2005 agus is beag a rinne sé: sheinn cnaipe gorm fuaim áiféiseach agus chroith fuinneog an bhrabhsálaí.", "Rinneadh anailís ar an SWF a tháinig slán chun íomhánna an chnaipe, an fhuaim agus amlíne chruinn 166 croitheadh a fháil ar ais. Seinneann Web Audio anois é gan bhreiseán Flash.", "Is breiseanna nua iad inrochtaineacht, 51 teanga, an cuntar domhanda agus liosta na dtacadóirí. Tá an leathanach bán folamh agus a jóc ait fós slán.", "Foinsí", "Ar ais chuig an gcnaipe"],
  cy: ["Hanes", "teuteuteu.com, darn wedi’i adfer o we’r 2000au", "Wedi’i gofnodi ar-lein erbyn 2005, prin oedd y dudalen Flash wreiddiol yn ei wneud: roedd botwm glas yn chwarae sain hurt tra oedd ffenestr y porwr yn ysgwyd.", "Dadansoddwyd yr SWF oedd wedi goroesi i adfer delweddau’r botwm, y sain ac union linell amser 166 o ysgytiadau. Mae Web Audio bellach yn ei chwarae heb ategyn Flash.", "Mae hygyrchedd, 51 iaith, y rhifydd byd-eang a’r rhestr gefnogwyr yn ychwanegiadau modern. Mae’r dudalen wen wag a’i jôc ryfedd yn aros yn gyfan.", "Ffynonellau", "Yn ôl at y botwm"],
  is: ["Saga", "teuteuteu.com, endurheimtur hluti af vef 2000-áranna", "Upprunalega Flash-síðan var skráð á netinu árið 2005 og gerði nánast ekkert: blár hnappur spilaði fáránlegt hljóð á meðan vafraglugginn skalf.", "Varðveitta SWF-skráin var greind til að endurheimta hnappamyndirnar, hljóðið og nákvæma tímalínu 166 hristinga. Web Audio spilar hana nú án Flash-viðbótar.", "Aðgengi, 51 tungumál, alþjóðlegi teljarinn og stuðningslistinn eru nútímalegar viðbætur. Tóma hvíta síðan og undarlegi brandarinn hennar standa óbreytt.", "Heimildir", "Aftur að hnappinum"],
  mt: ["Storja", "teuteuteu.com, biċċa restawrata tal-web tas-snin 2000", "Iddokumentata online sa mill-2005, il-paġna Flash oriġinali kważi ma kienet tagħmel xejn: buttuna blu kienet iddoqq ħoss assurd waqt li t-tieqa tal-browser titħawwad.", "L-SWF li baqa’ ġie analizzat biex jiġu rkuprati l-istampi tal-buttuna, l-awdjo u l-kronoloġija eżatta ta’ 166 ċaqliq. Web Audio issa jdoqqha mingħajr plugin Flash.", "L-aċċessibbiltà, 51 lingwa, il-counter globali u l-lista ta’ sostenituri huma żidiet moderni. Il-paġna bajda vojta u ċ-ċajta stramba tagħha jibqgħu intatti.", "Sorsi", "Lura għall-buttuna"],
  ar: ["التاريخ", "teuteuteu.com، قطعة مرمّمة من ويب الألفينات", "وُثّقت صفحة فلاش الأصلية على الإنترنت منذ عام 2005، ولم تكن تفعل إلا القليل: زر أزرق يشغّل صوتًا عبثيًا بينما تهتز نافذة المتصفح.", "حُلّل ملف SWF الباقي لاستعادة صور الزر والصوت والتسلسل الدقيق لـ166 اهتزازًا. ويعيد Web Audio تشغيله الآن من دون إضافة فلاش.", "إمكانية الوصول و51 لغة والعداد العالمي وقائمة الداعمين إضافات حديثة. أما الصفحة البيضاء الفارغة ونكتتها الغريبة فبقيتا كما هما.", "المصادر", "العودة إلى الزر"],
  he: ["היסטוריה", "teuteuteu.com, פיסה משוחזרת מהרשת של שנות ה־2000", "עמוד הפלאש המקורי תועד ברשת כבר ב־2005 וכמעט לא עשה דבר: כפתור כחול השמיע צליל אבסורדי בזמן שחלון הדפדפן רעד.", "קובץ ה־SWF ששרד נותח כדי לשחזר את תמונות הכפתור, הצליל וציר הזמן המדויק של 166 רעידות. Web Audio מנגן אותו כעת ללא תוסף פלאש.", "נגישות, 51 שפות, המונה העולמי ורשימת התומכים הם תוספות מודרניות. הדף הלבן הריק והבדיחה המוזרה שלו נשארו שלמים.", "מקורות", "חזרה לכפתור"],
  fa: ["تاریخچه", "teuteuteu.com، بخشی بازسازی‌شده از وب دههٔ ۲۰۰۰", "صفحهٔ اصلی فلش از سال ۲۰۰۶ در وب ثبت شده بود و تقریباً کاری نمی‌کرد: یک دکمهٔ آبی صدایی عجیب پخش می‌کرد و پنجرهٔ مرورگر می‌لرزید.", "فایل SWF باقی‌مانده برای بازیابی تصاویر دکمه، صدا و زمان‌بندی دقیق ۱۶۶ لرزش تحلیل شد. Web Audio اکنون آن را بدون افزونهٔ فلش اجرا می‌کند.", "دسترس‌پذیری، ۵۱ زبان، شمارندهٔ جهانی و فهرست حامیان افزوده‌های امروزی‌اند. صفحهٔ سفید خالی و شوخی عجیبش دست‌نخورده مانده‌اند.", "منابع", "بازگشت به دکمه"],
  ur: ["تاریخ", "teuteuteu.com، 2000 کی دہائی کے ویب کا بحال شدہ حصہ", "اصل فلیش صفحہ 2005 تک آن لائن درج ہو چکا تھا اور تقریباً کچھ نہیں کرتا تھا: نیلا بٹن ایک بےتکا سا ساؤنڈ چلاتا اور براؤزر کی کھڑکی ہلتی تھی۔", "محفوظ SWF کا تجزیہ کر کے بٹن کی تصاویر، آڈیو اور 166 جھٹکوں کی درست ٹائم لائن واپس لائی گئی۔ Web Audio اب اسے فلیش پلگ اِن کے بغیر چلاتا ہے۔", "رسائی، 51 زبانیں، عالمی کاؤنٹر اور معاونین کی فہرست جدید اضافے ہیں۔ خالی سفید صفحہ اور اس کا عجیب مذاق جوں کا توں ہیں۔", "ذرائع", "بٹن پر واپس جائیں"],
  hi: ["इतिहास", "teuteuteu.com, 2000 के दशक के वेब का पुनर्स्थापित अंश", "मूल Flash पेज 2005 तक ऑनलाइन दर्ज था और लगभग कुछ नहीं करता था: एक नीला बटन बेतुकी आवाज़ बजाता था और ब्राउज़र की खिड़की हिलती थी।", "बचे हुए SWF का विश्लेषण करके बटन की तस्वीरें, ऑडियो और 166 झटकों की सटीक समयरेखा वापस पाई गई। Web Audio अब इसे Flash प्लगइन के बिना चलाता है।", "सुलभता, 51 भाषाएँ, वैश्विक काउंटर और समर्थकों की सूची आधुनिक जोड़ हैं। खाली सफेद पेज और उसका अजीब मज़ाक जस का तस है।", "स्रोत", "बटन पर वापस जाएँ"],
  bn: ["ইতিহাস", "teuteuteu.com, ২০০০-এর দশকের ওয়েবের পুনরুদ্ধার করা অংশ", "মূল Flash পাতাটি ২০০৬ সালেই অনলাইনে নথিভুক্ত ছিল এবং প্রায় কিছুই করত না: একটি নীল বোতাম উদ্ভট শব্দ বাজাত আর ব্রাউজারের জানালা কাঁপত।", "সংরক্ষিত SWF বিশ্লেষণ করে বোতামের ছবি, অডিও এবং ১৬৬টি ঝাঁকুনির সঠিক সময়রেখা উদ্ধার করা হয়েছে। Web Audio এখন Flash প্লাগইন ছাড়াই তা চালায়।", "অ্যাক্সেসিবিলিটি, ৫১টি ভাষা, বিশ্বব্যাপী কাউন্টার এবং সমর্থকদের তালিকা আধুনিক সংযোজন। খালি সাদা পাতা ও তার অদ্ভুত রসিকতা অক্ষত আছে।", "উৎস", "বোতামে ফিরে যান"],
  id: ["Sejarah", "teuteuteu.com, potongan web tahun 2000-an yang dipulihkan", "Didokumentasikan daring sejak 2005, halaman Flash aslinya hampir tidak melakukan apa-apa: satu tombol biru memutar suara absurd sambil jendela peramban bergetar.", "SWF yang tersisa dianalisis untuk memulihkan gambar tombol, audio, dan urutan tepat 166 guncangan. Web Audio kini memutarnya tanpa plugin Flash.", "Aksesibilitas, 51 bahasa, penghitung global, dan daftar pendukung adalah tambahan modern. Halaman putih kosong dan lelucon anehnya tetap utuh.", "Sumber", "Kembali ke tombol"],
  ms: ["Sejarah", "teuteuteu.com, cebisan web tahun 2000-an yang dipulihkan", "Didokumentasikan dalam talian sejak 2005, halaman Flash asal hampir tidak melakukan apa-apa: satu butang biru memainkan bunyi pelik sementara tetingkap pelayar bergegar.", "SWF yang terselamat dianalisis untuk mendapatkan semula imej butang, audio dan urutan tepat 166 gegaran. Web Audio kini memainkannya tanpa pemalam Flash.", "Kebolehcapaian, 51 bahasa, pembilang global dan senarai penyokong ialah tambahan moden. Halaman putih kosong dan jenaka peliknya kekal utuh.", "Sumber", "Kembali ke butang"],
  vi: ["Lịch sử", "teuteuteu.com, một mảnh web thập niên 2000 được phục dựng", "Được ghi nhận trên mạng từ năm 2005, trang Flash nguyên bản hầu như không làm gì: một nút xanh phát âm thanh kỳ quặc trong khi cửa sổ trình duyệt rung lên.", "Tệp SWF còn lại được phân tích để khôi phục hình ảnh nút, âm thanh và dòng thời gian chính xác của 166 lần rung. Web Audio giờ tái hiện nó mà không cần plugin Flash.", "Khả năng truy cập, 51 ngôn ngữ, bộ đếm toàn cầu và danh sách người ủng hộ là các bổ sung hiện đại. Trang trắng trống và trò đùa kỳ lạ vẫn nguyên vẹn.", "Nguồn", "Quay lại nút"],
  th: ["ประวัติ", "teuteuteu.com ชิ้นส่วนเว็บยุค 2000 ที่ได้รับการบูรณะ", "หน้า Flash ดั้งเดิมมีหลักฐานออนไลน์ตั้งแต่ปี 2005 และแทบไม่ทำอะไรเลย: ปุ่มสีน้ำเงินเล่นเสียงประหลาดพร้อมกับหน้าต่างเบราว์เซอร์ที่สั่น", "ไฟล์ SWF ที่เหลืออยู่ถูกวิเคราะห์เพื่อกู้ภาพปุ่ม เสียง และลำดับเวลาที่แม่นยำของการสั่น 166 ครั้ง ปัจจุบัน Web Audio เล่นลำดับนี้โดยไม่ต้องใช้ปลั๊กอิน Flash", "การเข้าถึง 51 ภาษา ตัวนับทั่วโลก และรายชื่อผู้สนับสนุนเป็นส่วนเพิ่มเติมสมัยใหม่ ส่วนหน้าสีขาวว่างเปล่าและมุกแปลก ๆ ยังคงเหมือนเดิม", "แหล่งข้อมูล", "กลับไปที่ปุ่ม"],
  ja: ["歴史", "teuteuteu.com、2000年代のウェブから復元された一片", "2005年にはすでにネット上で記録されていた元のFlashページは、ほとんど何もしませんでした。青いボタンが不条理な音を鳴らし、ブラウザのウィンドウが揺れるだけでした。", "残されたSWFを解析し、ボタン画像、音声、166回の揺れの正確なタイムラインを復元しました。現在はWeb AudioがFlashプラグインなしで再現します。", "アクセシビリティ、51言語、世界共通カウンター、支援者一覧は現代の追加要素です。空白の白いページと奇妙な冗談はそのまま残されています。", "資料", "ボタンに戻る"],
  ko: ["역사", "teuteuteu.com, 2000년대 웹에서 복원한 한 조각", "2005년부터 온라인에 기록된 원래 Flash 페이지는 거의 아무것도 하지 않았습니다. 파란 버튼이 황당한 소리를 내고 브라우저 창이 흔들릴 뿐이었습니다.", "남아 있던 SWF를 분석해 버튼 이미지, 오디오, 166번 흔들림의 정확한 타임라인을 복원했습니다. 이제 Web Audio가 Flash 플러그인 없이 이를 재현합니다.", "접근성, 51개 언어, 전 세계 카운터와 후원자 목록은 현대에 추가된 기능입니다. 텅 빈 흰 페이지와 이상한 농담은 그대로 남아 있습니다.", "출처", "버튼으로 돌아가기"],
  "zh-CN": ["历史", "teuteuteu.com，一块复原的 2000 年代网页遗迹", "早在 2005 年，原版 Flash 页面就已有网络记录。它几乎什么也不做：一个蓝色按钮播放荒诞的声音，同时浏览器窗口开始震动。", "我们分析了留存的 SWF，找回按钮图片、音频以及 166 次震动的精确时间线。现在由 Web Audio 在无需 Flash 插件的情况下重现。", "无障碍支持、51 种语言、全球计数器和赞助者名单都是现代新增内容。空白页面和它奇怪的笑话仍保持原样。", "资料来源", "返回按钮"],
  "zh-TW": ["歷史", "teuteuteu.com，一塊復原的 2000 年代網頁遺跡", "早在 2005 年，原版 Flash 頁面就已有網路記錄。它幾乎什麼也不做：一個藍色按鈕播放荒謬的聲音，同時瀏覽器視窗開始震動。", "我們分析了留存的 SWF，找回按鈕圖片、音訊以及 166 次震動的精確時間軸。現在由 Web Audio 在不需 Flash 外掛的情況下重現。", "無障礙支援、51 種語言、全球計數器和贊助者名單都是現代新增內容。空白頁面和它奇怪的笑話仍保持原樣。", "資料來源", "返回按鈕"],
} as const satisfies Record<SupportedLocale, HistoryTuple>;

export function historyMessagesFor(locale: SupportedLocale): HistoryMessages {
  const [link, title, original, restoration, modern, sources, back] = translations[locale];
  return { link, title, original, restoration, modern, sources, back };
}
