import type { SupportedLocale } from "@/lib/i18n";

export type SupportMessages = {
  title: string;
  domain: string;
  month: string;
  year: string;
  optionalUpgrade: string;
  estimatedTotal: string;
  estimateNote: string;
  surePrompt: string;
  kibblePrompt: string;
  close: string;
};

const translations = {
  en: { title: "What keeps teuteuteu online", domain: "Domain", month: "month", year: "year", optionalUpgrade: "Optional upgrade", estimatedTotal: "Current estimate", estimateNote: "Excluding taxes and overages.", surePrompt: "Are you sure?", kibblePrompt: "A tiny tip for my kibble?", close: "Close hosting costs" },
  fr: { title: "Ce qui maintient teuteuteu en ligne", domain: "Domaine", month: "mois", year: "an", optionalUpgrade: "Upgrade facultatif", estimatedTotal: "Estimation actuelle", estimateNote: "Hors taxes et dépassements.", surePrompt: "Vous êtes sûr ?", kibblePrompt: "Un p’tit tip pour mes croquettes ?", close: "Fermer les coûts d’hébergement" },
  de: { title: "Was teuteuteu online hält", domain: "Domain", month: "Monat", year: "Jahr", optionalUpgrade: "Optionales Upgrade", estimatedTotal: "Aktuelle Schätzung", estimateNote: "Ohne Steuern und Mehrverbrauch.", surePrompt: "Ganz sicher?", kibblePrompt: "Ein kleiner Tipp fürs Katzenfutter?", close: "Hostingkosten schließen" },
  es: { title: "Lo que mantiene teuteuteu en línea", domain: "Dominio", month: "mes", year: "año", optionalUpgrade: "Mejora opcional", estimatedTotal: "Estimación actual", estimateNote: "Sin impuestos ni excesos de uso.", surePrompt: "¿Seguro?", kibblePrompt: "¿Una propinita para mis croquetas?", close: "Cerrar costes de alojamiento" },
  it: { title: "Cosa mantiene teuteuteu online", domain: "Dominio", month: "mese", year: "anno", optionalUpgrade: "Upgrade facoltativo", estimatedTotal: "Stima attuale", estimateNote: "Tasse e consumi extra esclusi.", surePrompt: "Sei sicuro?", kibblePrompt: "Una piccola mancia per i croccantini?", close: "Chiudi i costi di hosting" },
  "pt-PT": { title: "O que mantém o teuteuteu online", domain: "Domínio", month: "mês", year: "ano", optionalUpgrade: "Melhoria opcional", estimatedTotal: "Estimativa atual", estimateNote: "Sem impostos nem utilização extra.", surePrompt: "Tens a certeza?", kibblePrompt: "Uma pequena ajuda para a ração?", close: "Fechar custos de alojamento" },
  "pt-BR": { title: "O que mantém o teuteuteu online", domain: "Domínio", month: "mês", year: "ano", optionalUpgrade: "Upgrade opcional", estimatedTotal: "Estimativa atual", estimateNote: "Sem impostos nem uso excedente.", surePrompt: "Tem certeza?", kibblePrompt: "Uma gorjetinha para a minha ração?", close: "Fechar custos de hospedagem" },
  nl: { title: "Wat teuteuteu online houdt", domain: "Domein", month: "maand", year: "jaar", optionalUpgrade: "Optionele upgrade", estimatedTotal: "Huidige schatting", estimateNote: "Exclusief belasting en extra verbruik.", surePrompt: "Weet je het zeker?", kibblePrompt: "Een kleine fooi voor mijn brokjes?", close: "Hostingkosten sluiten" },
  pl: { title: "Co utrzymuje teuteuteu online", domain: "Domena", month: "miesiąc", year: "rok", optionalUpgrade: "Opcjonalne ulepszenie", estimatedTotal: "Bieżący szacunek", estimateNote: "Bez podatków i nadwyżek.", surePrompt: "Na pewno?", kibblePrompt: "Mały napiwek na karmę?", close: "Zamknij koszty hostingu" },
  cs: { title: "Co udržuje teuteuteu online", domain: "Doména", month: "měsíc", year: "rok", optionalUpgrade: "Volitelné vylepšení", estimatedTotal: "Aktuální odhad", estimateNote: "Bez daní a nadlimitní spotřeby.", surePrompt: "Opravdu?", kibblePrompt: "Malé spropitné na granule?", close: "Zavřít náklady na hosting" },
  sk: { title: "Čo udržiava teuteuteu online", domain: "Doména", month: "mesiac", year: "rok", optionalUpgrade: "Voliteľné vylepšenie", estimatedTotal: "Aktuálny odhad", estimateNote: "Bez daní a nadmerného využitia.", surePrompt: "Naozaj?", kibblePrompt: "Malý príspevok na granule?", close: "Zavrieť náklady na hosting" },
  hu: { title: "Ami online tartja a teuteuteu-t", domain: "Domain", month: "hónap", year: "év", optionalUpgrade: "Opcionális bővítés", estimatedTotal: "Jelenlegi becslés", estimateNote: "Adók és túlfogyasztás nélkül.", surePrompt: "Biztos vagy benne?", kibblePrompt: "Egy kis borravaló a cicakajára?", close: "Tárhelyköltségek bezárása" },
  ro: { title: "Ce menține teuteuteu online", domain: "Domeniu", month: "lună", year: "an", optionalUpgrade: "Upgrade opțional", estimatedTotal: "Estimare actuală", estimateNote: "Fără taxe și depășiri.", surePrompt: "Ești sigur?", kibblePrompt: "Un mic bacșiș pentru bobițe?", close: "Închide costurile de găzduire" },
  bg: { title: "Какво поддържа teuteuteu онлайн", domain: "Домейн", month: "месец", year: "година", optionalUpgrade: "Незадължителен ъпгрейд", estimatedTotal: "Текуща оценка", estimateNote: "Без данъци и превишена употреба.", surePrompt: "Сигурни ли сте?", kibblePrompt: "Малък бакшиш за котешка храна?", close: "Затвори разходите за хостинг" },
  el: { title: "Τι κρατά το teuteuteu online", domain: "Τομέας", month: "μήνα", year: "έτος", optionalUpgrade: "Προαιρετική αναβάθμιση", estimatedTotal: "Τρέχουσα εκτίμηση", estimateNote: "Χωρίς φόρους και υπερβάσεις.", surePrompt: "Είστε σίγουροι;", kibblePrompt: "Ένα μικρό φιλοδώρημα για γατοτροφή;", close: "Κλείσιμο κόστους φιλοξενίας" },
  tr: { title: "Teuteuteu’yu çevrimiçi tutanlar", domain: "Alan adı", month: "ay", year: "yıl", optionalUpgrade: "İsteğe bağlı yükseltme", estimatedTotal: "Güncel tahmin", estimateNote: "Vergiler ve aşım ücretleri hariç.", surePrompt: "Emin misiniz?", kibblePrompt: "Mama için küçük bir bahşiş?", close: "Barındırma maliyetlerini kapat" },
  ru: { title: "Что поддерживает teuteuteu онлайн", domain: "Домен", month: "месяц", year: "год", optionalUpgrade: "Необязательное улучшение", estimatedTotal: "Текущая оценка", estimateNote: "Без налогов и перерасхода.", surePrompt: "Вы уверены?", kibblePrompt: "Немного на кошачий корм?", close: "Закрыть расходы на хостинг" },
  uk: { title: "Що підтримує teuteuteu онлайн", domain: "Домен", month: "місяць", year: "рік", optionalUpgrade: "Необов’язкове покращення", estimatedTotal: "Поточна оцінка", estimateNote: "Без податків і перевитрат.", surePrompt: "Ви впевнені?", kibblePrompt: "Трохи на котячий корм?", close: "Закрити витрати на хостинг" },
  sv: { title: "Det som håller teuteuteu online", domain: "Domän", month: "månad", year: "år", optionalUpgrade: "Valfri uppgradering", estimatedTotal: "Aktuell uppskattning", estimateNote: "Exklusive skatt och överförbrukning.", surePrompt: "Är du säker?", kibblePrompt: "En liten slant till kattmaten?", close: "Stäng hostingkostnader" },
  no: { title: "Det som holder teuteuteu på nett", domain: "Domene", month: "måned", year: "år", optionalUpgrade: "Valgfri oppgradering", estimatedTotal: "Gjeldende estimat", estimateNote: "Uten avgifter og overforbruk.", surePrompt: "Er du sikker?", kibblePrompt: "En liten slant til kattematen?", close: "Lukk driftskostnader" },
  da: { title: "Det der holder teuteuteu online", domain: "Domæne", month: "måned", year: "år", optionalUpgrade: "Valgfri opgradering", estimatedTotal: "Aktuelt estimat", estimateNote: "Eksklusive skat og overforbrug.", surePrompt: "Er du sikker?", kibblePrompt: "En lille skilling til kattemaden?", close: "Luk hostingudgifter" },
  fi: { title: "Mikä pitää teuteuteun verkossa", domain: "Verkkotunnus", month: "kuukausi", year: "vuosi", optionalUpgrade: "Valinnainen päivitys", estimatedTotal: "Nykyinen arvio", estimateNote: "Ilman veroja ja ylityksiä.", surePrompt: "Oletko varma?", kibblePrompt: "Pieni tippi kissanruokaan?", close: "Sulje palvelinkulut" },
  et: { title: "Mis hoiab teuteuteu võrgus", domain: "Domeen", month: "kuu", year: "aasta", optionalUpgrade: "Valikuline uuendus", estimatedTotal: "Praegune hinnang", estimateNote: "Ilma maksude ja ülekuluta.", surePrompt: "Kas oled kindel?", kibblePrompt: "Väike jootraha kassitoiduks?", close: "Sulge majutuskulud" },
  lv: { title: "Kas uztur teuteuteu tiešsaistē", domain: "Domēns", month: "mēnesis", year: "gads", optionalUpgrade: "Izvēles jauninājums", estimatedTotal: "Pašreizējā aplēse", estimateNote: "Bez nodokļiem un pārtēriņa.", surePrompt: "Vai tiešām?", kibblePrompt: "Neliels dzeramnaudas kaķu barībai?", close: "Aizvērt mitināšanas izmaksas" },
  lt: { title: "Kas palaiko teuteuteu internete", domain: "Domenas", month: "mėnuo", year: "metai", optionalUpgrade: "Pasirenkamas atnaujinimas", estimatedTotal: "Dabartinis įvertis", estimateNote: "Be mokesčių ir viršijimų.", surePrompt: "Ar tikrai?", kibblePrompt: "Maža arbatpinigė kačių maistui?", close: "Uždaryti prieglobos išlaidas" },
  sl: { title: "Kaj ohranja teuteuteu na spletu", domain: "Domena", month: "mesec", year: "leto", optionalUpgrade: "Izbirna nadgradnja", estimatedTotal: "Trenutna ocena", estimateNote: "Brez davkov in prekoračitev.", surePrompt: "Ste prepričani?", kibblePrompt: "Majhen prispevek za mačjo hrano?", close: "Zapri stroške gostovanja" },
  hr: { title: "Što održava teuteuteu online", domain: "Domena", month: "mjesec", year: "godina", optionalUpgrade: "Neobavezna nadogradnja", estimatedTotal: "Trenutna procjena", estimateNote: "Bez poreza i prekoračenja.", surePrompt: "Jeste li sigurni?", kibblePrompt: "Mala napojnica za mačju hranu?", close: "Zatvori troškove hostinga" },
  sr: { title: "Шта одржава teuteuteu онлајн", domain: "Домен", month: "месец", year: "година", optionalUpgrade: "Опциона надоградња", estimatedTotal: "Тренутна процена", estimateNote: "Без пореза и прекорачења.", surePrompt: "Да ли сте сигурни?", kibblePrompt: "Мали прилог за храну за мачке?", close: "Затвори трошкове хостинга" },
  bs: { title: "Šta održava teuteuteu online", domain: "Domena", month: "mjesec", year: "godina", optionalUpgrade: "Opcionalna nadogradnja", estimatedTotal: "Trenutna procjena", estimateNote: "Bez poreza i prekoračenja.", surePrompt: "Jeste li sigurni?", kibblePrompt: "Mala napojnica za mačju hranu?", close: "Zatvori troškove hostinga" },
  sq: { title: "Çfarë e mban teuteuteu online", domain: "Domeni", month: "muaj", year: "vit", optionalUpgrade: "Përmirësim opsional", estimatedTotal: "Vlerësimi aktual", estimateNote: "Pa taksa dhe tejkalime.", surePrompt: "Je i sigurt?", kibblePrompt: "Një bakshish i vogël për ushqimin e maces?", close: "Mbyll kostot e hostimit" },
  ca: { title: "El que manté teuteuteu en línia", domain: "Domini", month: "mes", year: "any", optionalUpgrade: "Millora opcional", estimatedTotal: "Estimació actual", estimateNote: "Sense impostos ni excessos.", surePrompt: "N’estàs segur?", kibblePrompt: "Una propineta per al pinso?", close: "Tanca els costos d’allotjament" },
  eu: { title: "Teuteuteu sarean mantentzen duena", domain: "Domeinua", month: "hilabete", year: "urte", optionalUpgrade: "Aukerako hobekuntza", estimatedTotal: "Uneko estimazioa", estimateNote: "Zergak eta gehiegizko erabilera kanpo.", surePrompt: "Ziur zaude?", kibblePrompt: "Katu-janarirako propina txiki bat?", close: "Itxi ostalaritza-kostuak" },
  gl: { title: "O que mantén teuteuteu en liña", domain: "Dominio", month: "mes", year: "ano", optionalUpgrade: "Mellora opcional", estimatedTotal: "Estimación actual", estimateNote: "Sen impostos nin excesos.", surePrompt: "Estás seguro?", kibblePrompt: "Unha propiniña para o penso?", close: "Pechar custos de aloxamento" },
  ga: { title: "Cad a choinníonn teuteuteu ar líne", domain: "Fearann", month: "mí", year: "bliain", optionalUpgrade: "Uasghrádú roghnach", estimatedTotal: "Meastachán reatha", estimateNote: "Gan cánacha ná ró-úsáid.", surePrompt: "An bhfuil tú cinnte?", kibblePrompt: "Leid bheag do bhia an chait?", close: "Dún costais óstála" },
  cy: { title: "Beth sy’n cadw teuteuteu ar-lein", domain: "Parth", month: "mis", year: "blwyddyn", optionalUpgrade: "Uwchraddiad dewisol", estimatedTotal: "Amcangyfrif cyfredol", estimateNote: "Heb drethi na gorddefnydd.", surePrompt: "Wyt ti’n siŵr?", kibblePrompt: "Tip bach at fwyd y gath?", close: "Cau costau gwe-letya" },
  is: { title: "Það sem heldur teuteuteu á netinu", domain: "Lén", month: "mánuður", year: "ár", optionalUpgrade: "Valfrjáls uppfærsla", estimatedTotal: "Núverandi áætlun", estimateNote: "Án skatta og umframnotkunar.", surePrompt: "Ertu viss?", kibblePrompt: "Smá þjórfé fyrir kattamat?", close: "Loka hýsingarkostnaði" },
  mt: { title: "Dak li jżomm teuteuteu online", domain: "Dominju", month: "xahar", year: "sena", optionalUpgrade: "Titjib fakultattiv", estimatedTotal: "Stima attwali", estimateNote: "Mingħajr taxxi u użu żejjed.", surePrompt: "Żgur?", kibblePrompt: "Tip żgħir għall-ikel tal-qattus?", close: "Agħlaq l-ispejjeż tal-hosting" },
  ar: { title: "ما يُبقي teuteuteu متصلًا", domain: "النطاق", month: "شهر", year: "سنة", optionalUpgrade: "ترقية اختيارية", estimatedTotal: "التقدير الحالي", estimateNote: "باستثناء الضرائب والاستخدام الزائد.", surePrompt: "هل أنت متأكد؟", kibblePrompt: "إكرامية صغيرة لطعام القط؟", close: "إغلاق تكاليف الاستضافة" },
  he: { title: "מה משאיר את teuteuteu באוויר", domain: "דומיין", month: "חודש", year: "שנה", optionalUpgrade: "שדרוג אופציונלי", estimatedTotal: "הערכה נוכחית", estimateNote: "לא כולל מסים וחריגות.", surePrompt: "בטוחים?", kibblePrompt: "טיפ קטן לאוכל לחתול?", close: "סגירת עלויות האחסון" },
  fa: { title: "هزینه‌های آنلاین ماندن teuteuteu", domain: "دامنه", month: "ماه", year: "سال", optionalUpgrade: "ارتقای اختیاری", estimatedTotal: "برآورد فعلی", estimateNote: "بدون مالیات و مصرف اضافی.", surePrompt: "مطمئنید؟", kibblePrompt: "یک کمک کوچک برای غذای گربه؟", close: "بستن هزینه‌های میزبانی" },
  ur: { title: "teuteuteu کو آن لائن رکھنے کے اخراجات", domain: "ڈومین", month: "مہینہ", year: "سال", optionalUpgrade: "اختیاری اپ گریڈ", estimatedTotal: "موجودہ تخمینہ", estimateNote: "ٹیکس اور اضافی استعمال کے بغیر۔", surePrompt: "کیا آپ کو یقین ہے؟", kibblePrompt: "بلی کے کھانے کے لیے چھوٹی سی ٹپ؟", close: "ہوسٹنگ کے اخراجات بند کریں" },
  hi: { title: "teuteuteu को ऑनलाइन रखने का खर्च", domain: "डोमेन", month: "महीना", year: "वर्ष", optionalUpgrade: "वैकल्पिक अपग्रेड", estimatedTotal: "वर्तमान अनुमान", estimateNote: "कर और अतिरिक्त उपयोग शामिल नहीं।", surePrompt: "क्या आप निश्चित हैं?", kibblePrompt: "बिल्ली के खाने के लिए छोटी-सी टिप?", close: "होस्टिंग लागत बंद करें" },
  bn: { title: "teuteuteu অনলাইনে রাখার খরচ", domain: "ডোমেইন", month: "মাস", year: "বছর", optionalUpgrade: "ঐচ্ছিক আপগ্রেড", estimatedTotal: "বর্তমান হিসাব", estimateNote: "কর ও অতিরিক্ত ব্যবহার বাদে।", surePrompt: "আপনি নিশ্চিত?", kibblePrompt: "বিড়ালের খাবারের জন্য ছোট্ট টিপ?", close: "হোস্টিং খরচ বন্ধ করুন" },
  id: { title: "Yang membuat teuteuteu tetap online", domain: "Domain", month: "bulan", year: "tahun", optionalUpgrade: "Peningkatan opsional", estimatedTotal: "Perkiraan saat ini", estimateNote: "Di luar pajak dan kelebihan pemakaian.", surePrompt: "Anda yakin?", kibblePrompt: "Sedikit tip untuk makanan kucing?", close: "Tutup biaya hosting" },
  ms: { title: "Yang memastikan teuteuteu kekal dalam talian", domain: "Domain", month: "bulan", year: "tahun", optionalUpgrade: "Naik taraf pilihan", estimatedTotal: "Anggaran semasa", estimateNote: "Tidak termasuk cukai dan penggunaan berlebihan.", surePrompt: "Anda pasti?", kibblePrompt: "Sedikit tip untuk makanan kucing?", close: "Tutup kos pengehosan" },
  vi: { title: "Chi phí duy trì teuteuteu trực tuyến", domain: "Tên miền", month: "tháng", year: "năm", optionalUpgrade: "Nâng cấp tùy chọn", estimatedTotal: "Ước tính hiện tại", estimateNote: "Chưa gồm thuế và phí vượt mức.", surePrompt: "Bạn chắc chứ?", kibblePrompt: "Một chút tiền cho thức ăn mèo nhé?", close: "Đóng chi phí lưu trữ" },
  th: { title: "ค่าใช้จ่ายที่ทำให้ teuteuteu ออนไลน์", domain: "โดเมน", month: "เดือน", year: "ปี", optionalUpgrade: "อัปเกรดเพิ่มเติม", estimatedTotal: "ประมาณการปัจจุบัน", estimateNote: "ไม่รวมภาษีและการใช้งานเกิน", surePrompt: "แน่ใจหรือ?", kibblePrompt: "ทิปเล็ก ๆ สำหรับอาหารแมวไหม?", close: "ปิดค่าโฮสติ้ง" },
  ja: { title: "teuteuteu の運営費", domain: "ドメイン", month: "月", year: "年", optionalUpgrade: "任意のアップグレード", estimatedTotal: "現在の見積もり", estimateNote: "税金と超過料金は含みません。", surePrompt: "本当にいいの？", kibblePrompt: "猫のごはんに少しだけチップを？", close: "ホスティング費用を閉じる" },
  ko: { title: "teuteuteu 운영 비용", domain: "도메인", month: "월", year: "년", optionalUpgrade: "선택적 업그레이드", estimatedTotal: "현재 예상 비용", estimateNote: "세금 및 초과 사용료 제외.", surePrompt: "정말 괜찮으신가요?", kibblePrompt: "고양이 사료를 위한 작은 팁?", close: "호스팅 비용 닫기" },
  "zh-CN": { title: "teuteuteu 的在线成本", domain: "域名", month: "月", year: "年", optionalUpgrade: "可选升级", estimatedTotal: "当前估算", estimateNote: "不含税费和超额用量。", surePrompt: "确定不帮一下吗？", kibblePrompt: "给猫粮留一点小费？", close: "关闭托管成本" },
  "zh-TW": { title: "teuteuteu 的上線成本", domain: "網域", month: "月", year: "年", optionalUpgrade: "可選升級", estimatedTotal: "目前估算", estimateNote: "不含稅費與超額用量。", surePrompt: "確定不幫一下嗎？", kibblePrompt: "給貓糧留一點小費？", close: "關閉主機成本" },
} as const satisfies Record<SupportedLocale, SupportMessages>;

export function supportMessagesFor(locale: SupportedLocale): SupportMessages {
  return translations[locale];
}
